### ISSUE TITLE
Panic From Sort

### ISSUE THREAD

**Issue by nelsam** [nelsam/vidar#58]
The new sorting logic apparently has an index out of range problem.

```
panic: runtime error: index out of range

goroutine 5 [running]:
panic(0x463aae0, 0xc42000c110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nelsam/vidar/suggestions.(*Adapter).Sort(0xc42018c000, 0xc4204d7beb, 0x3)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/suggestions/suggestion_adapter.go:42 +0x2da
github.com/nelsam/vidar/editor.(*CodeEditor).updateSuggestionList(0xc420018600)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/editor/editor.go:329 +0x354
github.com/nelsam/vidar/editor.(*CodeEditor).ShowSuggestionList(0xc420018600)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/editor/editor.go:285 +0x5d
github.com/nelsam/vidar/editor.(*CodeEditor).KeyPress(0xc420018600, 0x5, 0x0, 0x4a40800)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/editor/editor.go:376 +0x31d
github.com/nelsam/gxui.(*KeyboardController).keyPress(0xc420248df0, 0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/keyboard_controller.go:42 +0x99
github.com/nelsam/gxui.(*KeyboardController).keyDown(0xc420248df0, 0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/keyboard_controller.go:28 +0x12c
github.com/nelsam/gxui.(*KeyboardController).(github.com/nelsam/gxui.keyDown)-fm(0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/keyboard_controller.go:15 +0x3e
reflect.Value.call(0x45c78a0, 0xc420248e00, 0x13, 0x46e8a23, 0x4, 0xc42097eb60, 0x1, 0x1, 0x46ad820, 0x465c6e0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x45c78a0, 0xc420248e00, 0x13, 0xc42097eb60, 0x1, 0x1, 0xc4204d77f0, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/nelsam/gxui.(*EventBase).InvokeListeners(0xc4202e0320, 0xc4204d77d0, 0x1, 0x1)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/event_base.go:140 +0x2d0
github.com/nelsam/gxui.(*EventBase).Fire(0xc4202e0320, 0xc4204d77d0, 0x1, 0x1)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/event_base.go:190 +0x75
github.com/nelsam/gxui/mixins.(*Window).setViewport.func9(0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/mixins/window.go:376 +0xcf
reflect.Value.call(0x45c78a0, 0xc420249050, 0x13, 0x46e8a23, 0x4, 0xc42097eb40, 0x1, 0x1, 0xc4202dbe78, 0x465c6e0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x45c78a0, 0xc420249050, 0x13, 0xc42097eb40, 0x1, 0x1, 0x46efe20, 0xc, 0x17)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/nelsam/gxui.(*EventBase).InvokeListeners(0xc4201cd358, 0xc4203f54a0, 0x1, 0x1)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/event_base.go:140 +0x2d0
github.com/nelsam/gxui.(*ChanneledEvent).Fire.func1()
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/channeled_event.go:36 +0x7c
github.com/nelsam/gxui/drivers/gl.(*driver).applicationLoop(0xc420236300)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/drivers/gl/driver.go:108 +0x6f
created by github.com/nelsam/gxui/drivers/gl.StartDriver
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/drivers/gl/driver.go:58 +0x32b
```

**Comment by nelsam** [comment]
Solved one problem, created another:

```
panic: ItemAt index 0 is out of bounds [0, -1]

goroutine 20 [running]:
panic(0x462c180, 0xc4203521e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nelsam/gxui.(*DefaultAdapter).ItemAt(0xc4201fa000, 0x0, 0x0, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/default_adapter.go:82 +0x270
github.com/nelsam/vidar/editor.(*CodeEditor).updateSuggestionList(0xc420018600)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/editor/editor.go:330 +0x391
github.com/nelsam/vidar/editor.(*CodeEditor).ShowSuggestionList(0xc420018600)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/editor/editor.go:285 +0x5d
github.com/nelsam/vidar/editor.(*CodeEditor).KeyPress(0xc420018600, 0x5, 0x0, 0x4a40800)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/vidar/editor/editor.go:376 +0x31d
github.com/nelsam/gxui.(*KeyboardController).keyPress(0xc42000cf30, 0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/keyboard_controller.go:42 +0x99
github.com/nelsam/gxui.(*KeyboardController).keyDown(0xc42000cf30, 0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/keyboard_controller.go:28 +0x12c
github.com/nelsam/gxui.(*KeyboardController).(github.com/nelsam/gxui.keyDown)-fm(0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/keyboard_controller.go:15 +0x3e
reflect.Value.call(0x45c78a0, 0xc42000cf40, 0x13, 0x46e8a23, 0x4, 0xc42041e500, 0x1, 0x1, 0x46ad820, 0x465c6e0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x45c78a0, 0xc42000cf40, 0x13, 0xc42041e500, 0x1, 0x1, 0xc42038a310, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/nelsam/gxui.(*EventBase).InvokeListeners(0xc4202e8320, 0xc42038a2f0, 0x1, 0x1)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/event_base.go:140 +0x2d0
github.com/nelsam/gxui.(*EventBase).Fire(0xc4202e8320, 0xc42038a2f0, 0x1, 0x1)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/event_base.go:190 +0x75
github.com/nelsam/gxui/mixins.(*Window).setViewport.func9(0x5, 0x0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/mixins/window.go:376 +0xcf
reflect.Value.call(0x45c78a0, 0xc42000d190, 0x13, 0x46e8a23, 0x4, 0xc42041e4e0, 0x1, 0x1, 0xc4201e1e78, 0x465c6e0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x45c78a0, 0xc42000d190, 0x13, 0xc42041e4e0, 0x1, 0x1, 0x46efe20, 0xc, 0x17)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/nelsam/gxui.(*EventBase).InvokeListeners(0xc4201e3358, 0xc4203b13a0, 0x1, 0x1)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/event_base.go:140 +0x2d0
github.com/nelsam/gxui.(*ChanneledEvent).Fire.func1()
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/channeled_event.go:36 +0x7c
github.com/nelsam/gxui/drivers/gl.(*driver).applicationLoop(0xc42024e0c0)
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/drivers/gl/driver.go:108 +0x6f
created by github.com/nelsam/gxui/drivers/gl.StartDriver
	/tmp/github.com/nelsam/vidar/src/github.com/nelsam/gxui/drivers/gl/driver.go:58 +0x32b
```
